export { default as Footer } from './footer'
export { default as Main } from './main'
export { default as Navigation } from './navigation'
export { default as About } from './about'
export { default as BlogList } from './blogList'
export { default as BlogDetail } from './blogDetail'
export { default as Social } from './social'
